#!/usr/bin/env bash
# Scan installed and optionally isolated Intel LLVM headers for native FP4/BDPAS APIs.
# This script is source-scan only: it does not compile, run GPU probes, install packages,
# or modify oneAPI/Level Zero installations.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
DEFAULT_OUTPUT="${ROOT_DIR}/activation/native-fp4-bdpas-capability.md"
OUTPUT_PATH="${DEFAULT_OUTPUT}"
LLVM_ROOT=""

INSTALLED_DPAS_HEADER="/opt/intel/oneapi/compiler/2025.3/include/sycl/ext/intel/esimd/xmx/dpas.hpp"
INSTALLED_COMMON_HEADER="/opt/intel/oneapi/compiler/2025.3/include/sycl/ext/intel/esimd/xmx/common.hpp"
PATTERN='bdpas|e2m1|fp4'

usage() {
    cat <<'USAGE'
usage: check-sycl-native-fp4-bdpas.sh [--output <path>] [--llvm-root <path>]

Scans installed Intel oneAPI SYCL ESIMD XMX headers for public native FP4/BDPAS
surface area and optionally scans an isolated Intel LLVM checkout for source
candidates. The scanner writes only the requested report file and refuses output
paths under /opt/intel/oneapi.
USAGE
}

error() {
    echo "error: $*" >&2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            if [[ $# -lt 2 ]]; then
                error "--output requires a path"
                exit 2
            fi
            OUTPUT_PATH="$2"
            shift 2
            ;;
        --llvm-root)
            if [[ $# -lt 2 ]]; then
                error "--llvm-root requires a path"
                exit 2
            fi
            LLVM_ROOT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            error "unknown argument: $1"
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -n "${LLVM_ROOT}" && ! -d "${LLVM_ROOT}" ]]; then
    error "--llvm-root must be an existing directory: ${LLVM_ROOT}"
    exit 2
fi

output_dir="."
output_base="${OUTPUT_PATH}"
if [[ "${OUTPUT_PATH}" == */* ]]; then
    output_dir="${OUTPUT_PATH%/*}"
    output_base="${OUTPUT_PATH##*/}"
fi
if [[ -z "${output_dir}" ]]; then
    output_dir="/"
fi
if [[ -z "${output_base}" || "${output_base}" == "." || "${output_base}" == ".." ]]; then
    error "--output must name a report file, not a directory"
    exit 2
fi

case "${OUTPUT_PATH}" in
    /opt/intel/oneapi|/opt/intel/oneapi/*)
        error "refusing to write under /opt/intel/oneapi: ${OUTPUT_PATH}"
        exit 2
        ;;
esac

# Refuse paths whose nearest existing parent resolves under /opt/intel/oneapi
# before creating any missing directories.
if [[ "${output_dir}" = /* ]]; then
    probe_dir="${output_dir}"
else
    probe_dir="${PWD}/${output_dir}"
fi
probe_existing="${probe_dir}"
while [[ ! -e "${probe_existing}" ]]; do
    parent="${probe_existing%/*}"
    if [[ "${parent}" == "${probe_existing}" || -z "${parent}" ]]; then
        parent="/"
    fi
    probe_existing="${parent}"
 done
probe_physical="$(cd "${probe_existing}" && pwd -P)"
case "${probe_physical}" in
    /opt/intel/oneapi|/opt/intel/oneapi/*)
        error "refusing to write under /opt/intel/oneapi: ${OUTPUT_PATH}"
        exit 2
        ;;
esac

mkdir -p "${output_dir}"
output_parent_physical="$(cd "${output_dir}" && pwd -P)"
case "${output_parent_physical}" in
    /opt/intel/oneapi|/opt/intel/oneapi/*)
        error "refusing to write under /opt/intel/oneapi: ${OUTPUT_PATH}"
        exit 2
        ;;
esac
OUTPUT_FILE="${output_parent_physical}/${output_base}"

header_has_pattern() {
    local regex="$1"
    shift
    local file
    for file in "$@"; do
        if [[ -f "${file}" ]] && grep -Eiq -- "${regex}" "${file}"; then
            return 0
        fi
    done
    return 1
}

installed_dpas_exists=0
installed_common_exists=0
[[ -f "${INSTALLED_DPAS_HEADER}" ]] && installed_dpas_exists=1
[[ -f "${INSTALLED_COMMON_HEADER}" ]] && installed_common_exists=1

bdpas_present=0
fp4_e2m1_present=0
native_fp4_usable=0
if header_has_pattern 'bdpas' "${INSTALLED_DPAS_HEADER}" "${INSTALLED_COMMON_HEADER}"; then
    bdpas_present=1
fi
if header_has_pattern 'e2m1|fp4' "${INSTALLED_DPAS_HEADER}" "${INSTALLED_COMMON_HEADER}"; then
    fp4_e2m1_present=1
fi
if [[ "${bdpas_present}" -eq 1 && "${fp4_e2m1_present}" -eq 1 ]]; then
    native_fp4_usable=1
fi

source_candidate_paths=()
if [[ -n "${LLVM_ROOT}" ]]; then
    while IFS= read -r rel_path; do
        [[ -n "${rel_path}" ]] || continue
        source_candidate_paths+=("${rel_path#./}")
    done < <(cd "${LLVM_ROOT}" && grep -RIlE -- "${PATTERN}" . 2>/dev/null | sort)
fi
source_candidate_count="${#source_candidate_paths[@]}"

usable_reason="available"
if [[ "${native_fp4_usable}" -eq 0 ]]; then
    usable_reason="missing_public_installed_bdpas_or_fp4_e2m1_api"
fi

{
    echo "# Native FP4/BDPAS Capability Report"
    echo
    echo "Generated by scripts/check-sycl-native-fp4-bdpas.sh."
    echo
    echo '```text'
    echo "native_fp4.usable=${native_fp4_usable}"
    echo "native_fp4.usable_reason=${usable_reason}"
    echo "bdpas.present=${bdpas_present}"
    echo "fp4_e2m1.present=${fp4_e2m1_present}"
    echo "installed.dpas_header=${INSTALLED_DPAS_HEADER}"
    echo "installed.dpas_header.exists=${installed_dpas_exists}"
    echo "installed.common_header=${INSTALLED_COMMON_HEADER}"
    echo "installed.common_header.exists=${installed_common_exists}"
    if [[ -n "${LLVM_ROOT}" ]]; then
        llvm_root_physical="$(cd "${LLVM_ROOT}" && pwd -P)"
        echo "llvm_root=${llvm_root_physical}"
    else
        echo "llvm_root="
    fi
    echo "source_candidates.count=${source_candidate_count}"
    if [[ "${source_candidate_count}" -gt 0 ]]; then
        for i in "${!source_candidate_paths[@]}"; do
            printf 'source_candidates.path.%d=%s\n' "$((i + 1))" "${source_candidate_paths[$i]}"
        done
    fi
    echo '```'
    echo
    echo "Notes:"
    echo "- This is a header/source scan only; it does not compile kernels or run GPU probes."
    echo "- Native FP4 is marked usable only when installed public headers expose both BDPAS and FP4/E2M1 API names."
    echo "- The scanner does not install packages and refuses report output under /opt/intel/oneapi."
} > "${OUTPUT_FILE}"

echo "wrote ${OUTPUT_FILE}"
